- src/api/__test__/errors.test.ts
- src/service/impl/geocoder.ts
- src/service/impl/journey.ts
- src/service/impl/stops.ts
- src/service/types.ts
Maps the following system errors from requests upstream to 503:
- ECONNRESET
- ECONNREFUSED
- ENOTFOUND
- EPIPE
- ETIMEDOUT
Adds test cases for errors
Closes #2
> better error responses for upstream errors

- src/api/__test__/stops.test.ts
- src/api/stops/index.ts
- src/api/stops/schema.ts
- src/service/impl/stops.ts
- src/service/interface.ts
- src/service/types.ts
In preparation of new functionality in route planner:
- GET /stops/nearest?lat=NUMBER&lon=NUMBER:
Queries NSR for the nearest stop places
- GET /stops?query=Kongens gate&lat=63.433&lon=10.322
Convenience for first querying geocoder with query, and sources = 'venue'. Filters the results for stops with a valid NSR id and queries NSR for the resulting IDs. `lat` and `lon` are optional
> Improve stops

- src/api/__test__/errors.test.ts
- src/api/__test__/journey.test.ts
- src/api/journey/index.ts
- src/api/journey/schema.ts
- src/service/impl/journey.ts
- src/service/interface.ts
- src/service/types.ts
- src/utils/journey-utils.ts
This is kind of odd, but as it is now, Entur doesn't provide a way to get one particular trip pattern suggestion ofter having searched for it. This makes navigating, real-time polling, and many other things difficult.
This adds a very rudimentary workaround for this issue by storing the original query, the time of the query, and the service journeys from the trip pattern as a base64-encoded ID passed to the client. We can use that client to do another search and find the same trip suggestion. The thing is: Sometimes you don't get the same result (high traffic stops for instance), so now it looks like searching for 20 suggestions does the trick. Not an ideal solution, but OK for now to avoid spending way to much time on this.
A possible extension at some point can be to add an outer cache …
> Adds endpoint for fetching one specific journey trip pattern

- src/api/stops/index.ts
- src/api/stops/schema.ts
- src/service/impl/stops.ts
- src/service/interface.ts
- src/service/types.ts
- tsconfig.json
Adds own endpoint for generated departures by stop place and quay. This will replace the previously used nearest and stops endpoints and instead work on "Location" type. From the app, it is oblivious if the passed location is a venue or not. This also allows us to have consistent behavior across clients at some point.
There are several improvements that could be made at some point. Most notably for fetching additional results, but thinking this can be fixed as a part of https://github.com/AtB-AS/mittatb-app/issues/255. 
Another point we can think about at some point is caching.
> feat(departure): Adds endpint POST /v1/departures 

- src/api/__test__/errors.test.ts
- src/api/__test__/geocoder.test.ts
- src/api/__test__/journey.test.ts
- src/api/__test__/stops.test.ts
- src/api/stops/index.ts
- src/api/stops/schema.ts
- src/service/types.ts
- swagger.yaml
Not as ambiguous naming for the endpoint. Also fixes path with new `/bff` prefix. This also bumps  swagger.yaml
> Renames endpoint POST /departures to POST /departures-from-location

- src/graphql/graphql-client.ts
Avoid being rate limited too aggressively by Entur for GraphQL requests
> fix: adds client info to graphql client

- src/api/geocoder/schema.ts
- src/service/types.ts
- swagger.yaml
Necessary for tariff zone selection in app where only venues within ATB
tariff zones should be selectable.
> feat: Support tariff zone authorities

- src/api/stops/schema.ts
- src/service/impl/stops/utils/grouping.ts
Just to make it easier to use with favorites there is no need to give bad request just because there are some surplus data.
(Also I added another change to piggyback on this, which is a bad thing to do, but I did it anyway. The change is to fix issue with lines not getting filtered out from stops that are not favorites)
> fixes: strips unknown properties for favorites in stop scheme

- src/service/impl/geocoder.ts
- src/service/types.ts
- src/types/entur.d.ts
Adding this initial code to get the feature. I'm planning on sending a PR to Entur SDK with the additional properties so we don't have to override here, but to be able to test in staging and fine-tune the focus weighting I'm adding this code now.
I've added ENV `GEOCODER_FOCUS_WEIGHT` to be able to override the weighting without deploying new code.
> feat: adds support for focus point

- src/plugins/logfmt.ts
There are some errors in the staging, but I can't find any way to actually trace the errors, but in Error reporter in GCP and log tracing.
I don't know if this will help, as it seems as the logfmt output is just JSON in any case? I'm having a hard time tracking the logic/flow of logging here.
> adds stack trace to logging

- src/service/impl/stops/utils/grouping.ts
Currently, when treating Public Code as a string we don't get a natural sort for numbers. Which causes 11 to be sorted before 2 etc. But also we can't guarantee that all public codes are numbers. So this checks if it is a number and if it is we sort by the parsed number.
> fix: use natural number sorting for public codes if numbers

- Dockerfile
Closes #87 
Graceful shutdown is handled by the `hapi-pulse` plugin, so we don't need our own handler.
> fix: make node the docker entrypoint

- Readme.md
Ser at man blir bedt om å klone "atb-as/bff-oneclick-planner" istedet for "atb-as/atb-bff" i readme. Forslag om å forandre til ny URL.
> docs: update git repo url in readme

- src/api/__test__/journey.test.ts
- src/api/journey/schema.ts
- src/service/types.ts
- Øker antall trips til max 15
- Setter "straff" på gange til 5 (opp fra 4)
- Setter maks gange før reisemetode til 2km (fra uendelig)
- Setter eksplisitt maks gange mellom overføringer til 2km.
Enda ikke testet i reell kjøring men oppretter PR for kontekst
> feat: more trip results, penalty for walking, max walking distance

- src/api/stops/schema.ts
- src/service/impl/stops/index.ts
- src/service/types.ts
Ny avganger visning i appen er avhengig av å hente ut stopPlaces i nærheten, og da vil jeg ikke ha med ubrukte quays. Parameteren `includeUnusedQuays` er derfor fin å kunne sette.
> feat: add `includeUnusedQuays` on `getStopPlacesByPosition`

- package-lock.json
- package.json
Oppdaterer til en Hapi-versjon som støtter nyeste LTS av Node (16).
---
Dette unngå feil med null statusCode i versjon av Node over 14.
> fix: updates hapi version to support node 16

- src/api/departures/index.ts
- src/api/departures/schema.ts
- src/service/impl/departures/gql/jp3/quay-departures.graphql
- src/service/impl/departures/gql/jp3/quay-departures.graphql-gen.ts
- src/service/impl/departures/gql/jp3/stops-nearest.graphql
- src/service/impl/departures/gql/jp3/stops-nearest.graphql-gen.ts
- src/service/impl/departures/index.ts
- src/service/interface.ts
- swagger.yaml
Legger til to endepunkt, som gir data til ny avganger-visning i appen.
- `/bff/v2/departures/quay-departures` 
- `/bff/v2/departures/stops-nearest`
Henger sammen med https://github.com/AtB-AS/mittatb-app/issues/1884 / https://github.com/AtB-AS/mittatb-app/pull/1885
> feat: Add departure endpoints

- src/service/impl/departures/gql/jp3/quay-departures.graphql
- src/service/impl/departures/gql/jp3/quay-departures.graphql-gen.ts
- src/service/impl/departures/gql/jp3/stop-departures.graphql
- src/service/impl/departures/gql/jp3/stop-departures.graphql-gen.ts
Det er ikke alle delene av graphQL spørringene som er i bruk i ny avganger visning, så de fjernes her for å spare (litt) på mobildata og minne når det er mange avganger som lastes.
> feat: remove unused data from departure queries

- src/api/departures/schema.ts
- src/service/impl/departures/gql/jp3/stop-departures.graphql
- src/service/impl/departures/gql/jp3/stop-departures.graphql-gen.ts
- src/service/impl/departures/index.ts
- swagger.yaml
For å gjøre oppførselen mellom `stopPlaceQuayDepartures` og [`quayDepartures`](https://github.com/AtB-AS/atb-bff/blob/master/src/service/impl/departures/gql/jp3/quay-departures.graphql#L1) likere, legger jeg til et `timeRange` parameter. Hvis jeg forstår det riktig, så er det ikke breaking, siden den er optional?
> feat: add timeRange parameter to stopPlaceQuayDepartures

- cloudbuild.yaml
Prøver å løse det slik at environment vars blir ikke overskrevet for hver deploy for BFF.
Dette fordrer at substitution variables settes på triggers i Cloud Build CC @mikaelbr
> chore: Substitution values and env vars

- src/graphql/journeyplanner-types_v3.ts
- src/service/impl/departures/gql/jp3/quay-departures.graphql
- src/service/impl/departures/gql/jp3/quay-departures.graphql-gen.ts
- src/service/impl/departures/gql/jp3/stop-departures.graphql
- src/service/impl/departures/gql/jp3/stop-departures.graphql-gen.ts
I sammenheng med sak https://github.com/AtB-AS/mittatb-app/issues/2090 trenger man å hente `aimedDepartureTime` som del av query StopPlaceDepartures og QuayDepartures. 
Oppdaterer også genererte JP3 typer i samme slengen.
> feat: add aimedDepartureTime to departures queries

- src/api/vipps-login/index.ts
Was missing `+`  before phone number while creating a new user.
> fix: add + before phone number while creating user as well

- src/service/impl/departures/gql/jp3/favourite-departure.graphql
- src/service/impl/departures/gql/jp3/favourite-departure.graphql-gen.ts
- src/service/impl/departures/utils/favorites.ts
Adds publicCode field to favourite-departure graphql query
Also applies formatting to favourite-departure.graphql-gen.ts, which shouldn't change any functionality.
> refactor: add publicCode field to favorite departures query

- src/service/impl/departures/gql/jp3/favourite-departure.graphql
- src/service/impl/departures/gql/jp3/favourite-departure.graphql-gen.ts
- src/service/impl/departures/index.ts
Adds realtime field to the favorite deparure query, in order to show "ca." on the correct departures
Fixes comment from QA https://github.com/AtB-AS/kundevendt/issues/1877#issuecomment-1240321388 (@HanneLH)
> refactor: add realtime field to favorite departure query

- src/graphql/graphql-client.ts
We discovered numerous issues around caching when deploying the bff to our own cluster.
We didn't specify any resource limits for the pods initially, but started observing unbounded memory growth. 
We applied some limits on both cpu and memory and observed that the node process was not able to respond to liveness probes from the cluster in a timely manner when CPU was throttled. This resulted in repeated restarts. CPU usage seemed to increase with memory growth.
After changing the deployment to use an image with the changes proposed in this PR, memory and cpu usage plummeted.
> Disable caching in graphql-client

- src/api/departures/schema.ts
- src/service/impl/departures/gql/jp3/quay-departures.graphql-gen.ts
- src/service/impl/departures/index.ts
This is needed to get one entry per line so that we can use that in improved favorites flow i.e. https://github.com/AtB-AS/kundevendt/issues/2593
> feat: expose limitPerLine attribute in APIs to get limited departures

- src/api/geocoder/index.ts
- swagger.yaml
This reverts commit 3cf6ae87ea6d0c1ade345b7c90ca4c0cf83a012c
@tormoseng Noticed that the `bff/v1/geocoder/features` endpoint is still in use when using autocomplete in search in the app. Therefore, the endpoint should not be deprecated.
> revert: "chore: deprecate endpoint `bff/v1/geocoder/features` (#168)"

- src/service/impl/service-journey/serviceJourney.ts
The GET `/bff/v2/servicejourney/{id}/polyline` endpoint was using the old journeyPlannerClient with OTP1, despite using OPT2 typing. Looks like an mistaken implementation introduced in e358e3ef6837c343c1e1a298bfde1ac96a70db22. 
This updates to `journeyPlannerClient_v3`, with OTP2.
This is a change that affects pre-existing versions of the app. So we should test older versions before we push this to prod.
> feat: upgrade map polyline endpoints to OTP2

- .github/workflows/api-tests.yml
An error causes the API tests to check out a deleted branch. Changed to `main`.
> fix: checkout main for api tests

- src/graphql/journeyplanner-types_v3.ts
- src/service/impl/departure-favorites/journey-gql/jp3/departure-group.graphql
- src/service/impl/departure-favorites/journey-gql/jp3/departure-group.graphql-gen.ts
- src/service/impl/departure-favorites/journey-gql/jp3/departure-time.graphql
- src/service/impl/departure-favorites/journey-gql/jp3/departure-time.graphql-gen.ts
In JP3 omitNonBoarding is now deprecated, and Entur said it was replaced by the field arrivalDeparture. A value of 'both' in arrivalDeparture should give the same as 'false' in omitNonBoarding.
More context:
https://mittatb.slack.com/archives/CHLDG8C30/p1668437703909409
Acceptance criteria:
> fix: Replace omitNonBoarding with arrivalDeparture

- src/api/servicejourney/index.ts
- src/api/servicejourney/schema.ts
- src/service/impl/fragments/jp3/estimated-calls.graphql
- src/service/impl/fragments/jp3/estimated-calls.graphql-gen.ts
- src/service/impl/fragments/jp3/notices.graphql
- src/service/impl/fragments/jp3/notices.graphql-gen.ts
- src/service/impl/fragments/jp3/quays.graphql
- src/service/impl/fragments/jp3/quays.graphql-gen.ts
- src/service/impl/fragments/jp3/service-journey.graphql
- src/service/impl/fragments/jp3/service-journey.graphql-gen.ts
- src/service/impl/fragments/jp3/stop-places.graphql
- src/service/impl/fragments/jp3/stop-places.graphql-gen.ts
- src/service/impl/service-journey/index.ts
- src/service/impl/service-journey/journey-gql/jp3/service-journey-departures.graphql
- src/service/impl/service-journey/journey-gql/jp3/service-journey-departures.graphql-gen.ts
- src/service/impl/service-journey/journey-gql/jp3/service-journey-with-estimated-calls.graphql
- src/service/impl/service-journey/journey-gql/jp3/service-journey-with-estimated-calls.graphql-gen.ts
- src/service/interface.ts
- src/service/types.ts
- swagger.yaml
The main new feature is adding notices, however since this was already a
non-backward compatible change the old ServiceJourneyDepartures endpoint
was replaced with a new ServiceJourneyWithEstimatedCalls endpoint to fix
some illogical structuring of the old query.
Some examples:
- The old endpoint retrieved serviceJourney fields through each
estimated call. This is not necessary as the root element is the
same serviceJourney that every call references.
- The old endpoint accessed the line (for publicCode) through
serviceJourney -> estimatedCall -> serviceJourney -> journeyPattern ->
line, when it could be serviceJourney -> line.
- TransportMode and TransportSubmode were queried on line when it can be
queried directly on the serviceJourney.
Also created reusable fragments for the fragments …
> feat: Add ServiceJourneyWithEstimatedCalls

- src/graphql/journeyplanner-types_v3.ts
- src/service/impl/departure-favorites/journey-gql/jp3/departure-group.graphql
- src/service/impl/departure-favorites/journey-gql/jp3/departure-group.graphql-gen.ts
- src/service/impl/departure-favorites/journey-gql/jp3/departure-time.graphql
- src/service/impl/departure-favorites/journey-gql/jp3/departure-time.graphql-gen.ts
Not entirely sure why this was set to `both`, but there may have been a reason that means we should keep this as-is. In OTP1, the equivalent field is called `omitNonBoarding`, and departures v1 have this set to `omitNonBoarding: false`. Do you remember @mikaelbr?
fixes https://github.com/AtB-AS/kundevendt/issues/3072
> fix: return departures only from departure favorites

- src/service/impl/departures/index.ts
Return error when receving a list with stop places that do not exist to avoid the app crashing
<details>
<summary>Screenshot</summary>
</details>
Close https://github.com/AtB-AS/kundevendt/issues/2558
> fix: Return err when stop place is null

- .github/workflows/api-tests.yml
- test/src/v2/servicejourney/servicejourney.ts
The `Run API tests` step does not fail the tests since the `| ...` is always successful. Adds a new step that fails the workflow (a cheapy trick, I know).
> test: step to fail the workflow if error

- test/src/config/configuration.ts
- test/src/k6.ts
- test/src/scenario.ts
- test/src/v1/departures/departures.ts
- test/src/v1/geocoder/geocoder.ts
- test/src/v1/journey/journey.ts
- test/src/v1/servicejourney/servicejourney.ts
- test/src/v1/v1Scenario.ts
- test/src/v2/departures/departures.ts
- test/src/v2/departures/favorites.ts
- test/src/v2/departures/stops.ts
- test/src/v2/servicejourney/servicejourney.ts
- test/src/v2/testData/testData.ts
- test/src/v2/trips/trips.ts
In case there is an error in a response, and the tests want to parse it as json, an error is thrown so that the rest of the tests are not run. This PR adds try-catch to be able to run the rest of the tests in case of an error - and output the error in a proper way.
This PR also fixes an error where the v1/journey/trip provided a servicejourney id for the servicejourney requests/tests. Now the endpoint /v2/trips is used instead.
> test: error handling for api tests

- src/api/realtime/schema.ts
- src/service/impl/departures-grouped/departure-group.ts
- src/service/impl/realtime/departure-time.ts
- src/service/impl/realtime/index.ts
- src/service/impl/realtime/journey-gql/departure-time.graphql
- src/service/impl/realtime/journey-gql/departure-time.graphql-gen.ts
- src/service/types.ts
Related to https://github.com/AtB-AS/mittatb-app/pull/3303
- Adds ability to filter realtime departures by lines, which is useful for favorites (both dashboard and departures in the app).
- Fixes an issue with caching of realtime departures due to missing `fetchPolicy`. (For reference: [Understanding Apollo Fetch Policies](https://medium.com/@galen.corey/understanding-apollo-fetch-policies-705b5ad71980))
resolves https://github.com/AtB-AS/kundevendt/issues/3252
> feat: add filter by line to realtime endpoint

- test/src/scenario.ts
- test/src/v2/mobility/index.ts
- test/src/v2/mobility/stations.ts
- test/src/v2/mobility/vehicles.ts
- test/src/v2/v2Scenario.ts
Added API-tests for:
- mobility/vehicles: searches in Oslo and verifies the results
- mobility/stations: searches in Trondheim and verifies the results
> test: api tests for mobility endpoints

- src/api/realtime/schema.ts
- src/service/impl/departures/index.ts
- src/service/impl/realtime/departure-time.ts
- src/service/types.ts
Adds `timeRange` as an optional param to realtime queries, and sets default to 24 hours instead of 22, since that's what's used as default everywhere else.
> feat: add timeRange query variable to realtime

- .github/workflows/api-tests.yml
- test/src/config/configuration.ts
- test/src/k6.ts
- test/src/v2/mobility/index.ts
- test/src/v2/mobility/scenario.ts
- test/src/v2/mobility/vehicles.ts
- test/src/v2/types/mobility.ts
- test/src/v2/v2Scenario.ts
Update the API tests with correct response from `v2/mobility/vehicles` and subsequent request for a specific vehicle id in `v2/mobility/vehicle`.
Also, update with the possibility to NOT output JUnit results as the log will be cleaner and easier to understand.
> test: update mobility API tests

- src/api/mobility/index.ts
- src/api/mobility/schema.ts
- src/graphql/mobility/mobility-types_v2.ts
- src/service/impl/fragments/mobility-gql/shared.graphql
- src/service/impl/fragments/mobility-gql/shared.graphql-gen.ts
- src/service/impl/fragments/mobility-gql/stations.graphql
- src/service/impl/fragments/mobility-gql/stations.graphql-gen.ts
- src/service/impl/fragments/mobility-gql/vehicles.graphql
- src/service/impl/fragments/mobility-gql/vehicles.graphql-gen.ts
- src/service/impl/mobility/index.ts
- src/service/impl/mobility/mobility-gql/stations.graphql
- src/service/impl/mobility/mobility-gql/stations.graphql-gen.ts
- src/service/impl/mobility/mobility-gql/vehicles.graphql
- src/service/impl/mobility/mobility-gql/vehicles.graphql-gen.ts
- src/service/interface.ts
- src/service/types.ts
Entur has introduced a new `ids` parameter to their `stations` and `vehicles` queries. This pr uses this new option to fetch a single scooter or station.
> feat: Fetch scooters and stations by id

- .github/workflows/api-tests.yml
- test/src/v2/mobility/scenario.ts
- test/src/v2/mobility/stations.ts
- test/src/v2/mobility/vehicles.ts
- test/src/v2/types/mobility.ts
- test/src/v2/v2Scenario.ts
Changed according to the mobility API: First get a list of el-scooters/bikes, and then get a single by id.
Note! Only testing one id in the list of ids. Will update this later.
> test: get vehicles by id

- src/graphql/graphql-client.ts
Fixes an issue where there is no `x-correlation-id` header returned from Entur.
> use hapi's correlationId instead of one returned from entur

- src/service/impl/service-journey/utils.ts
Change logic regarding COORDINATE_DISTANCE_THRESHOLD_IN_METERS, as it seems to be too short to find the nearest point on link in several cases, and then returns default, which is full color for the whole line:
<details>
<summary>Screenshot</summary>
</details>
With changing the logic to find the nearest point on link for the quay, it seems to fix most/all cases, and does not appear to break places:
<details>
<summary>Screenshot</summary>
</details>
Also add handling for from index and to index being first and last index, respectively.
Related to https://github.com/AtB-AS/kundevendt/issues/3689
> fix: Update logic for finding corresponding point on link

- src/graphql/graphql-client.ts
This is a stopgap solution while waiting for Entur to properly annotate rate limiting groups.
> Add `rateLimitGroup` field to GraphQL logs

- src/graphql/graphql-client.ts
Looks like the InMemoryCache was reset on every API call, since it was created inside the returned ApolloClient function. 
This change makes InMemoryCache persist between API calls, and fixes caching for realtime requests as observed in https://github.com/AtB-AS/kundevendt/issues/4131
fixes https://github.com/AtB-AS/kundevendt/issues/4131
> fix: make InMemoryCache persistent

- src/service/types.ts
BFF part of https://github.com/AtB-AS/mittatb-app/pull/3641
- Adds a `STATUS_CODES_TO_FORWARD` array with codes that we want to forward to the app. Right now just 429s, but since we probably want to handle more error cases in the future, I made it easily extendable.
I don't really think APIError should be part of types.ts, but I'm working on a refactor, that I'll make a new PR for.
> feat: forward 429 network errors

- src/graphql/journey/journeyplanner-types_v3.ts
- src/graphql/vehicles/vehicles-types_v1.ts
- src/service/impl/vehicles/vehicles-gql/vehicles.graphql
- src/service/impl/vehicles/vehicles-gql/vehicles.graphql-gen.ts
`Entur` recently added a new attribute to the GraphQL in order to know the end of a journey, this is useful for live position to know when it reached the end and show another option for `see live`
Closes: https://github.com/AtB-AS/kundevendt/issues/4214
> feat: Use of VehicleStatus property on GraphQL

- src/service/impl/realtime/departure-time.ts
- src/service/types.ts
Send aimedDepartureTime as part of the real-time response so that the app can differentiate different departures with the same `serviceJourneyId`. See https://github.com/AtB-AS/mittatb-app/pull/3699 for how it is used in the app. 
Part of solving https://github.com/AtB-AS/kundevendt/issues/4277
> feat: add aimedDepartureTime to realtime response

- src/api/departures-grouped/schema.ts
- src/api/departures/schema.ts
- src/api/enrollment/schema.ts
- src/api/geocoder/schema.ts
- src/api/mobility/index.ts
- src/api/mobility/schema.ts
- src/api/quays/schema.ts
- src/api/realtime/schema.ts
- src/api/servicejourney/schema.ts
- src/api/trips/schema.ts
- src/api/vehicles/schema.ts
- src/api/vipps-login/schema.ts
- src/service/impl/departures-grouped/departure-favorites.ts
- src/service/types.ts
After https://github.com/AtB-AS/atb-bff/pull/278, I noticed some small bugs with Joi validation schemas that would be much easier to spot if typescript types were used when setting up validation.
There was some inconsistencies that I have tried to fix without causing functional changes. I've added some comments to those places below.
Shouldn't be any functional changes, but could be a good idea to test these endpoints after merge: 
- `/bff/v2/mobility/stations`
- `/bff/v2/mobility/vehicles`
- `/bff/v2/departures/departures` (Through add favorite flow, and departures v2 filtered on favorites)
- `/bff/v1/journey/trip` (Only versions below v1.18 of the app)
> refactor: add types to Joi schemas

- src/api/mobility/index.ts
- src/api/mobility/schema.ts
- src/graphql/journey/journeyplanner-types_v3.ts
- src/service/impl/fragments/mobility-gql/shared.graphql
- src/service/impl/fragments/mobility-gql/shared.graphql-gen.ts
- src/service/impl/fragments/mobility-gql/vehicles.graphql
- src/service/impl/fragments/mobility-gql/vehicles.graphql-gen.ts
- src/service/impl/mobility/index.ts
- src/service/impl/mobility/mobility-gql/stations.graphql
- src/service/impl/mobility/mobility-gql/stations.graphql-gen.ts
- src/service/impl/mobility/mobility-gql/vehicles.graphql
- src/service/impl/mobility/mobility-gql/vehicles.graphql-gen.ts
- src/service/interface.ts
- src/service/types.ts
Part of https://github.com/AtB-AS/kundevendt/issues/7511
Introduces version 2 of the `vehicles` and `stations` endpoints. This is to accommodate for the changes necessary in https://github.com/AtB-AS/mittatb-app/pull/3764
> feat: Add support for free floating bicycles

- test/src/v2/departures/favorites.ts
Line 5001 is now going from Loddgårdstrøa, which not give similar results when comparing favorites (line 82) with all departures. Changed to departure time 16:00, when there's no school busses.
> test: change start time on api requests

- src/service/impl/mobility/mobility-gql/vehicles.graphql
- src/service/impl/mobility/mobility-gql/vehicles.graphql-gen.ts
Ryde has changed form factor from SCOOTER to SCOOTER_STANDING. We need to treat both these form factors as scooters.
Closes https://github.com/AtB-AS/kundevendt/issues/8649
Related app pr: https://github.com/AtB-AS/mittatb-app/pull/3866
> feat: Support form factor SCOOTER_STANDING

- src/service/impl/geocoder.ts
- src/types/geocoder.d.ts
See discussion https://mittatb.slack.com/archives/C02EEG7D8EL/p1696927561021349
Missing unit for focus causes focus point in geocoder not to work as expected. This enforces unit using types.
Fixes https://github.com/AtB-AS/kundevendt/issues/9263
> fix: issue with missing unit for scale in geocoder

- src/service/impl/mobility/index.ts
Found during the development of https://github.com/AtB-AS/kundevendt/issues/7908
> fix: Use correct Nivel url for vehicle lookup

- src/service/impl/mobility/index.ts
- src/service/types.ts
Nivel have changed their API and removed a few properties. The violations that previously had `selectable: false` are no longer sent
> fix: Updates after Nivel api changes

- src/api/mobility/index.ts
Found during testing of https://github.com/AtB-AS/kundevendt/issues/7908.
Images sent in parking violation reports are scaled down to around 1MB - sometimes under, sometimes over, depending on the image contents. The max limit could thus be set to something less than 10MB, but if image compression on the client fails on certain devices etc. the rather large limit will hopefully prevent errors due to an arbitrary limit at our end. Nivel accept these sizes.
> fix: Increase max payload size for parking violation reports

- src/api/mobility/schema.ts
Necessary in order to add the option "Unknown provider". Nivel accepts undefined here.
Corresponding app pr: https://github.com/AtB-AS/mittatb-app/pull/3967
> fix: Make providerId optional in parking violations report

- src/service/impl/departures-grouped/utils/grouping.ts
- src/service/impl/departures/utils/converters.ts
Resolves https://github.com/AtB-AS/kundevendt/issues/2732
Replaces legacy usage of frontText in the toKey function
Also adds a couple of comments
> chore: use destinationDisplay to create key

- src/api/mobility/schema.ts
Currently, not providing `range` to the stations or vehicles endpoints gives a 500 server error. Making the field required in the schema gives a more precise error message:
```
{
"statusCode": 400,
"error": "Bad Request",
"message": "\"range\" is required",
"validation": {
"source": "query",
"keys": [
"range"
]
}
}
```
- /bff/v2/mobility/stations_v2?lat=63.4279&lon=10.3888&includeBicycles=true&includeCars=true&range=1000
- /bff/v2/mobility/vehicles_v2?lat=63.4279&lon=10.3888&includeScooters=true&includeBicycles=true&range=1000
- /bff/v2/mobility/stations_v2?lat=63.4279&lon=10.3888&includeBicycles=true&includeCars=true
- /bff/v2/mobility/vehicles_v2?lat=63.4279&lon=10.3888&includeScooters=true&includeBicycles=true
> chore: make range a required field for stations and vehicles

- src/service/impl/mobility/index.ts
fixes part of https://github.com/AtB-AS/kundevendt/issues/15210
Since there are a lot of requests to stations_v2 where no stations are asked for, I think it makes sense to add a guard that returns an empty result before sending a request to Entur. And to vehicles_v2 in case it also applies there.
The best solution is of course to not send those requests in the first place, which I will look at next, but that will only apply to new versions of the app, so hopefully this makes the BFF a bit more performant and less noisy towards Entur.
> perf: prevent unnecessary mobility requests

- src/service/impl/fragments/mobility-gql/stations.graphql
- src/service/impl/fragments/mobility-gql/stations.graphql-gen.ts
Related to https://github.com/AtB-AS/kundevendt/issues/15241
Right now we don't have any information about station capacity, we need it to display the information to the user as shown in the screenshot below.
- The number 3 is the total available cars.
- The number 4 is the total station capacity.
Please let me know if I missed anything!
> feat: add capacity to station query

- src/api/departures/index.ts
- src/service/impl/departures/index.ts
- src/service/interface.ts
- src/service/types.ts
To allow for locally stored favorite departures in the app to be migrated with regards to via format changes, include `lineName` along with `destinationDisplay` for the EstimatedCalls.
Resolves https://github.com/AtB-AS/kundevendt/issues/2732
Relevant app PR: https://github.com/AtB-AS/mittatb-app/pull/4056
> feat: return lineName as well on EstimatedCalls for departures

- src/service/impl/fragments/mobility-gql/stations.graphql
- src/service/impl/fragments/mobility-gql/stations.graphql-gen.ts
Related to PR : https://github.com/AtB-AS/mittatb-app/pull/4049
Currently we don't have any ID for vehicles returned by the stations, this is needed to ensure that we use correct `key` for the vehicle list in a car station.
> feat: add vehicle id for mobility vehicles

- src/graphql/graphql-client.ts
- src/utils/api-error.ts
- src/utils/fetch-client.ts
1. Moves the `fetchWithTimeout` client to `fetch-client`
2. Uses fetchWithTimeout for non-graphql endpoints (geocoder / violations reporting)
3. Forwards 504 timeouts to clients
closes https://github.com/AtB-AS/kundevendt/issues/16023
> feat: forward 504 timeouts to clients

- src/api/vehicles/index.ts
@Nisha1306 informed me about a crash in production caused by an Apollo Error during setup of a websocket subscription. I'm not able to recreate the exact problem locally (because the actual error seemed to be a temporary one at Enturs end), but throwing an arbitrary error during setup of vehiclesSubscriptionClient, caused the BFF to crash.
Putting the entirety of createServiceJourneySubscription in a try/catch prevents my locally fabricated crash from happening, and the assumption is that it would catch any upstream errors as well.
> fix: catch errors when creating Apollo subscriptions

- src/graphql/journey/journeyplanner-types_v3.ts
- src/service/impl/fragments/mobility-gql/shared.graphql
- src/service/impl/fragments/mobility-gql/shared.graphql-gen.ts
To know which `systemId` to use for requesting geofencing zones, it must be included on the vehicle.
Note that for the future, it could be considered to also add this on `vehicleBasic`:
```gql
system {
id
}
```
This would allow the app to know the `systemId` immediately onClick rather than after the `/vehicle` call, however would also add about 30% more data to the `/vehicles` response.
Resolves https://github.com/AtB-AS/kundevendt/issues/17614
> feat: add system id for vehicle

- src/api/mobility/index.ts
- src/api/mobility/schema.ts
- src/graphql/journey/journeyplanner-types_v3.ts
- src/graphql/mobility/mobility-types_v2.ts
- src/service/impl/mobility/index.ts
- src/service/impl/mobility/mobility-gql/geofencing-zones.graphql
- src/service/impl/mobility/mobility-gql/geofencing-zones.graphql-gen.ts
- src/service/interface.ts
- src/service/types.ts
In order to support geofencing zones, add a new end point for Enturs Mobility API with graphql.
Example use: `/bff/v2/mobility/geofencing-zones?systemIds=voitrondheim`
closes https://github.com/AtB-AS/kundevendt/issues/17614
> feat: geofencing zones

- test/package.json
- test/src/config/performanceConfig.json
- test/src/scenario.ts
- test/src/utils/utils.ts
- test/yarn.lock
Doing trip searches, a date is needed. This time, the chosen day fell on May 17th.
Not a fail proof solution, but change the weekday for doing trip searches. Pre: Friday, which now is May 17th. Change to Thursday.
> test: Change day of week in trip search

- src/service/impl/mobility/index.ts
- src/service/impl/mobility/schema.ts
- src/service/types.ts
The logo image we get from Nivel can sometimes be `null`, which previously lead to an error https://mittatb.slack.com/archives/C0116FMPX4Y/p1715346138109749
This maps the `null` value to `undefined`, which is an expected option in the app.
> fix: handle null parking violation provider image

- test/src/v2/testData/testData.ts
On the test cases, there is only one /trip request and due to summer schedules there are less results than before. A quick fix is to lower the requested number of trip patterns for one specific test scenario: Skansen (place) -> Melhus (place).
> test: less results in summer

- src/api/stop-places/index.ts
- src/api/stop-places/schema.ts
- src/service/impl/stop-places/index.ts
- src/service/impl/stop-places/journey-gql/stop-place-parent.graphql
- src/service/impl/stop-places/journey-gql/stop-place-parent.graphql-gen.ts
- src/service/interface.ts
- src/service/types.ts
part of https://github.com/AtB-AS/kundevendt/issues/18275
Adds an endpoint to look for parent stop place ID, we can then use the parent ID to look up the departure details in some stops, instead of using the current reverse geocoder API.
Endpoint : `/bff/v2/stop-places/parent`
> feat: add endpoint for looking the parent ID of a stop place

- src/service/impl/stop-places/index.ts
This PR introduces a temporary flag to include the ferry submode in the stop places query. This change ensures backward compatibility for showing ferry stop places when buying express boat tickets in the Svipper app. This should be removed once we have enough users on the app version including the permanent solution: https://github.com/AtB-AS/mittatb-app/pull/4704. 
Part of closing https://github.com/AtB-AS/kundevendt/issues/18966
> feat: temporary flag to include ferry submode in stop places query

- test/package.json
- test/yarn.lock
Updated webpack-watched-glob-entries-plugin dependency since the new version also supports node version above 18.
> test: updated webpack-watched-glob-entries-plugin dependency

- src/api/stop-places/index.ts
Following https://github.com/AtB-AS/mittatb-app/pull/4735, `/bff/v2/stop-places/parent-id` can be deprecated.
> chore: deprecate parent-id endpoint

- src/plugins/__tests__/app-version-checker-plugin.test.ts
- src/plugins/app-version-checker-plugin.ts
- src/plugins/atb-headers.ts
- src/server.ts
- src/types/atb-headers.d.ts
- src/utils/__tests__/compare-version.test.ts
- src/utils/compare-version.ts
- src/utils/log-response.ts
If a MIN_APP_VERSION env variable is set, then all incoming requests
with app version in http header (atb-app-version) lower than the
minimum is rejected with status code 426 Upgrade Required.
> feat: Add app version checker plugin

- src/api/servicejourney/index.ts
Error "Cannot read properties of undefined (reading 'correlationId')" when using the polyline endpoint with no cache set.
```json
{
"time": "2024-11-12T08:54:51.646Z",
"method": "GET",
"url": "http://atb-prod.api.mittatb.no/bff/v2/servicejourney/ATB:ServiceJourney:1_240229121417009_73/polyline",
"requestId": "8bec0eb8-7250-4eba-8c07-5ae67846ddc8",
"installId": "92f54197-0724-441c-83d2-1773a2779a16",
"appVersion": "1.58",
"correlationId": "57eaa696-13bd-4da4-a998-f5bb67d8040f",
"message": "handle request",
"fromQuayId": "NSR:Quay:102721",
"error": "Cannot read properties of undefined (reading 'correlationId')",
"code": "500",
"severity": "ERROR",
"duration": "2ms"
}
```
The polyline server method has a third parameter
'headers: Request<ReqRefDefaults>', but this third parameter wasn't …
> fix: Polyline endpoint fail without cache

- src/plugins/__tests__/app-version-checker-plugin.test.ts
- src/plugins/app-version-checker-plugin.ts
Allows requests with no app version to prevent the widget from breaking. Also allows requests from app versions <1.24, (since they don't set the appVersion header) but since it's such a low amount of users, it's better than breaking the widget.
ref. https://mittatb.slack.com/archives/C0116FMPX4Y/p1732006029514839
> feat: allow requests with no appVersion header

- src/graphql/graphql-client.ts
- src/service/impl/departures-grouped/departure-favorites.ts
- src/service/impl/departures-grouped/departure-group.ts
- src/service/impl/departures/index.ts
- src/service/impl/realtime/__tests__/sanitize-realtime-query.test.ts
- src/service/impl/realtime/departure-time.ts
- src/service/impl/realtime/index.ts
- src/service/impl/realtime/sanitize-realtime-query.ts
- src/service/impl/service-journey/service-journey.ts
The theory is that the Apollo Client cache is the reason why we are
seeing a large memory usage in prod. Also the client doesn't make as
much sense when we have multiple BFF instances running in prod.
The main usage for the Apollo Client cache was to cache the previous
result for realtime updates, so only calls that were actually
updated could be returned. This is now changed to only return
updates for calls up to 30 minutes in the future, and no usage of
cache.
Here are some results of testing the realtime endpoint with old and new BFF where the new BFF does not use Apollo client cache, but instead restrict realtime updates to the next 30 minutes. 
The test was done around 10:30 AM a normal weekday.
| Case | Old BFF | New BFF |
| --- | --- | --- |
| Departures screen: P1 with date now | …
> feat: Disable the Apollo Client cache

- .github/workflows/api-tests.yml
- test/src/utils/utils.ts
- test/src/v2/departures/departures.ts
- test/src/v2/departures/favorites.ts
When doing travel searches and departure searches, the tests sometimes asks for a day that has weekend schedules. Added a simple solution where the search date is increased if such a date is picked.
Also changed search times from `00:00` to `03:00` to avoid getting departures from the previous day.
> test: handle holidays in api tests

- src/service/impl/geocoder.ts
- src/utils/temporarily-prioritize-world-cup-features.ts
If the "Granåsen Idrettspark" stop place  or "Granåsen Skistadion" POI appears in a geocoder autocomplete search, this moves them to the top of the list of results. Hopefully this will make it appear often enough, and prevent some confusion among Ski VM visitors.
ref. https://mittatb.slack.com/archives/CHLDG8C30/p1737474070199799
> feat: add geocoder hack to prioritize world cup features

- test/src/v2/departures/favorites.ts
- test/src/v2/testData/testData.ts
- test/src/v2/types/testData.ts
Line 82 has now become `Hesttrøa via Melhus skysstasjon` and `Hesttrøa`. Not only `Hesttrøa`, which now gives more list items in the favourite response that the tests have to handle.
https://github.com/AtB-AS/atb-bff/actions/runs/13026227256
> test: edit test data after route changes

- test/src/v2/testData/testData.ts
Prinsens gate P4 has been added and removed lately, making the API tests failing. Changing the test data to Kongens gate instead.
> test: change test data

- src/service/impl/geocoder.ts
In case we want to configure geocoder scale as an env variable, this should do it. E.g `GEOCODER_SCALE=300`.
> feat: add GEOCODER_SCALE env variable

- src/service/impl/service-journey/utils.ts
refer to this slack discussion: https://mittatb.slack.com/archives/C0116FMPX4Y/p1748107469811009
The issue here is that the `buss for tog`/`rail replacement bus` from Trondheim Lufthavn departs from a quay which is located a bit further from the polyline, so it fails to detect the departure point, and cannot generate a polyline to send in to the client.
I have increased the detection distance a bit higher to 250 metres away, it should still be within reasonable distance used normally, and works with the Trondheim Lufthavn case we have (the specific distance is 221 metres).
This will indirectly fix this bugsnag issue: https://app.bugsnag.com/atb-as/mittatb/errors/6788c603c88e184232652ed0?filters[event.since]=all&filters[app.release_stage]=store
> feat: increase distance limit polyline

- src/config/env.ts
With setting up the BFF for VKT/Farte, we noticed that the sales service is required for the BFF to run. Since it only affects the new booking endpoint we can set it to not be required.
> fix: make sales service non-required

- src/graphql/graphql-client.ts
This is done to avoid `Location: [object Object]` on errors
> fix: Added stringification of locations 
