AtB-AS/atb-bff

src/api/__test__/errors.test.ts
src/api/__test__/geocoder.test.ts
src/api/geocoder/schema.ts
src/service/impl/geocoder.ts
src/service/impl/journey.ts
src/service/impl/stops.ts
src/service/types.ts

Better errors

---

package-lock.json
package.json
src/index.ts
src/service/impl/entur.ts
src/utils/metrics.ts

- Fetch projectId from metadata server
- Move exporter initialisation

improve metrics reporting

---

src/service/impl/stops.ts

There's been some issue with missing departures. I think we should do this simpler and rather be "less smart" about this.
Have had multiple reports of departures missing, and I think this is the main reason for that.

Fix: no longer remove "irrelevant" departures on nearby

---

src/plugins/logfmt.ts
src/server.ts

... to please Stackdriver Logging

Experiment: log logfmt as JSON

---

src/api/journey/schema.ts

Related to https://github.com/AtB-AS/mittatb-app/issues/323

feat: Change transfer time to 30 seconds to have korrespondanse

---

src/service/impl/stops/index.ts

Related: https://github.com/AtB-AS/mittatb-app/issues/687

fix: ISO format for departure endpoint should be only date

---

src/service/impl/entur.ts

This isn't in use. The counters hog up some memory.

fix: remove opencensus telemtry

---

src/api/journey/schema.ts
src/api/stops/schema.ts

Fixes https://github.com/AtB-AS/mittatb-app/issues/1035

fix: allows for single item arrays in param schemas

---

Readme.md
src/index.ts

- Foreslår noen oppdateringer til Readme som forklarer hvordan man kan kjøre BFF lokalt uten Docker. (Også info om at man trenger node 14, så slipper andre å kaste bort tid på det 😬)
- Foreslår også til noen `console.info` -statements under oppstart, så er det enklere å se at serveren har startet opp.

docs: improvements for running server locally without docker

---

Dockerfile
Readme.md

Closes #94 
Eksempel:
```shell
docker build --target=dev -t atb-bff:dev .
docker run --rm -it -e PORT=8080 -p 8080:8080 -v /path/to/source:/app atb-bff:dev
```

feat: dev stage

---

src/service/impl/departures/gql/jp3/stop-departures.graphql
src/service/impl/departures/gql/jp3/stop-departures.graphql-gen.ts

Fiks av feil GraphQL spørring, og feilmelding:

fix: remove serviceJourney transportMode

---

src/utils/journey-utils.ts

https://github.com/AtB-AS/mittatb-app/issues/2070

fix: add padding to compressedQuery startTime

---

Readme.md
package.json

Fjerner notis på node versjon 14 da det er fikset og versjon er oppdatert. Se https://github.com/hapijs/hapi/pull/4295 for kontekst.

chore: remove notice on node version in readme

---

src/api/trips/schema.ts
src/service/impl/trips/graphql/jp3/trip.graphql
src/service/impl/trips/graphql/jp3/trip.graphql-gen.ts
swagger.yaml

BFF-del av AtB-AS/mittatb-app#2019
Legger til 4 optional parameter for Trips-endepunktet 
- transferPenalty
- waitReluctance
- walkReluctance
- walkSpeed

feat: add trip preferences to Trips query

---

src/service/impl/service-journey/index.ts
src/service/impl/service-journey/journey-gql/jp3/service-journey-map.graphql
src/service/impl/service-journey/journey-gql/jp3/service-journey-map.graphql-gen.ts
src/service/impl/service-journey/serviceJourney.ts
src/service/impl/service-journey/utils_v3.ts
src/service/types.ts

in departure details, toQuay is not relevant.
this PR handles calls to mapInfo with optional toQuay

fix:handle optional toQuay in mapInfo

---

Readme.md

Add info about previously encountered error, and fix.

docs: add project-id error to readme

---

src/service/impl/departures/gql/jp3/quay-departures.graphql
src/service/impl/departures/gql/jp3/quay-departures.graphql-gen.ts
src/service/impl/departures/gql/jp3/stop-departures.graphql
src/service/impl/departures/gql/jp3/stop-departures.graphql-gen.ts

Modifying the departure queries to fetch cancelled trips as well
Linked issue: https://github.com/AtB-AS/mittatb-app/issues/2695

modify departures queries to include cancelled trips

---

cloudbuild.yaml
src/api/enrollment/index.ts
src/config/env.ts

invite key for flex ticketing
https://github.com/AtB-AS/kundevendt/issues/1956

feat: flex ticketing enroll

---

src/api/departure-favorites/index.ts
swagger.yaml

follow up to https://github.com/AtB-AS/atb-bff/pull/149

refactor: add swagger config for departure favorite

---

src/api/trips/schema.ts
src/service/impl/trips/graphql/jp3/trip.graphql-gen.ts
src/utils/journey-utils.ts
swagger.yaml

Closes part of https://github.com/AtB-AS/kundevendt/issues/2374 
Exposes param to fetch trips with **directMode** specified

refactor: allow direct mode to be sent in trips search query

---

src/graphql/journeyplanner-types_v3.ts
src/service/impl/trips/graphql/jp3/trip.graphql
src/service/impl/trips/graphql/jp3/trip.graphql-gen.ts

I realized that instead of generating using the script I added the modes directly. So here are some changes to fix that. 
Closes part of https://github.com/AtB-AS/kundevendt/issues/2374

refactor: add directMode in graphql as well

---

src/graphql/journeyplanner-types_v3.ts
src/service/impl/trips/graphql/jp3/trip.graphql
src/service/impl/trips/graphql/jp3/trip.graphql-gen.ts

Adds stop place id in trips query, for from and to place. 
ref. https://github.com/AtB-AS/mittatb-app/pull/2990

feat: add stop place id for from and to in TripsQuery

---

src/api/geocoder/index.ts
swagger.yaml

ref https://github.com/AtB-AS/mittatb-app/pull/2993

chore: deprecate endpoint `bff/v1/geocoder/features`

---

src/graphql/journeyplanner-types_v3.ts
src/service/impl/departures/gql/jp3/quay-departures.graphql
src/service/impl/departures/gql/jp3/quay-departures.graphql-gen.ts

Add missing param in actual graphql query

refactor: add missing param in graph ql query

---

src/api/servicejourney/index.ts
src/api/servicejourney/schema.ts
src/service/impl/service-journey/index.ts
src/service/impl/service-journey/journey-gql/jp3/service-journey-departures.graphql
src/service/impl/service-journey/journey-gql/jp3/service-journey-departures.graphql-gen.ts
src/service/interface.ts

Adds endpoint `bff/v2/servicejourney/[id]/departures` for PR https://github.com/AtB-AS/mittatb-app/pull/3037, which upgrades DepartureDetails to OTP2.

feat: add otp2 departuredetails endpoint

---

swagger.yaml

Swagger config for https://github.com/AtB-AS/atb-bff/pull/176

chore: add swagger config for departure details v2

---

src/service/impl/departures/gql/jp3/quay-departures.graphql
src/service/impl/departures/gql/jp3/quay-departures.graphql-gen.ts
src/service/impl/departures/gql/jp3/stop-departures.graphql
src/service/impl/departures/gql/jp3/stop-departures.graphql-gen.ts

Resolves https://github.com/AtB-AS/kundevendt/issues/147

feat: Query situations on estimated calls

---

src/graphql/journeyplanner-types_v3.ts
src/service/impl/departure-favorites/journey-gql/jp3/departure-group.graphql-gen.ts
src/service/impl/departure-favorites/journey-gql/jp3/departure-time.graphql-gen.ts
src/service/impl/departures/gql/jp3/quay-departures.graphql-gen.ts
src/service/impl/departures/gql/jp3/stop-departures.graphql-gen.ts
src/service/impl/departures/gql/jp3/stops-details.graphql-gen.ts
src/service/impl/departures/gql/jp3/stops-nearest.graphql-gen.ts
src/service/impl/fragments/jp3/situations.graphql-gen.ts
src/service/impl/service-journey/journey-gql/jp3/service-journey-departures.graphql-gen.ts
src/service/impl/service-journey/journey-gql/jp3/service-journey-map.graphql-gen.ts
src/service/impl/trips/graphql/jp3/trip.graphql-gen.ts

Resolves https://github.com/AtB-AS/kundevendt/issues/2881

refactor: Some changes after running gql_gen_v3

---

test/src/v2/servicejourney/index.ts
test/src/v2/servicejourney/servicejourney.ts
test/src/v2/types/servicejourney.ts
test/src/v2/v2Scenario.ts

Missing test for new endpoint serviceJourneyCalls from #189

test: add serviceJourneyCalls to api tests

---

src/graphql/journeyplanner-types_v3.ts
src/service/impl/trips/graphql/jp3/trip.graphql
src/service/impl/trips/graphql/jp3/trip.graphql-gen.ts

Get actual departure time from dated service journey rather than service journey for realtime in trips.
https://github.com/AtB-AS/atb-bff/pull/196#issuecomment-1348633834
https://github.com/AtB-AS/kundevendt/issues/2949

feat: add dated service journey with actual departure time

---

src/api/__test__/servicejourney.test.ts
src/api/servicejourney/index.ts
src/api/servicejourney/schema.ts
src/service/impl/service-journey/index.ts
src/service/interface.ts
swagger.yaml

closes https://github.com/AtB-AS/kundevendt/issues/2849

feat: upgrade /bff/v1/servicejourney/{id}/departures to OTP2

---

src/api/servicejourney/index.ts
src/api/servicejourney/schema.ts
src/service/interface.ts

refactor: Typos

---

Readme.md

Update readme to reflect changes in #205

docs: update readme with new code-gen script

---

src/index.ts

Fix of 404 response to realtime endpoints after https://github.com/AtB-AS/atb-bff/pull/216

fix: add realtimeRoutes to index.ts

---

swagger.yaml

Update swagger with new realtime params

chore: update swagger

---

src/service/impl/departures-grouped/departure-favorites.ts
src/service/impl/departures/index.ts
src/service/impl/realtime/departure-time.ts

closes https://github.com/AtB-AS/kundevendt/issues/3205

feat: populate cache on initial departure requests

---

test/src/v2/departures/realtime.ts

Update ms in realtime request to not hit the cache.

test: handle cache

---

src/plugins/atb-headers.ts
src/plugins/logfmt.ts
src/server.ts
src/types/atb-headers.d.ts

Closes https://github.com/AtB-AS/team-platform/issues/279

improvise logging

---

.github/workflows/api-tests.yml
test/src/scenario.ts
test/src/utils/utils.ts
test/src/v2/departures/departures.ts
test/src/v2/departures/favorites.ts
test/src/v2/departures/realtime.ts
test/src/v2/testData/testData.ts
test/src/v2/trips/trips.ts
test/src/v2/types/departure.ts
test/src/v2/types/index.ts

There was a wrong type that was used due to some code changes along with some special cases in trip search related to bus departing schedule changes vs expected trip results.

test: api-test fixes

---

src/graphql/graphql-client.ts

Skips logging of GraphQL responses completely if no rate limiting headers are present.

conditional GraphQL logging & additional rate group

---

src/service/impl/trips/trips.ts

Due to an Entur bug (?) trip suggestions for rental bike sometimes contain only foot legs. This typically happens for short journeys in areas without rental bikes. This pr removes the trip suggestion when this happens.
Fixing this in BFF makes it easy to remove the fix when/if Entur fixes it.

fix: Remove rental bike trip suggestions with only foot legs

---

src/service/impl/stop-places/index.ts

Added a filter to remove to-stop-place which is the same as from-stop-place in boat ticket purchase

feat: Remove fromStopPlace as option for toStopPlace

---

src/graphql/journey/journeyplanner-types_v3.ts
src/graphql/vehicles/vehicles-types_v1.ts

Generated files were not up to date.
There are no changes to source files here, just the resulting changes of `npm run gql-gen`

fix: generate journey types

---

.gitignore
src/api/mobility/index.ts
src/api/mobility/schema.ts
src/config/env.ts
src/service/impl/mobility/index.ts
src/service/impl/mobility/schema.ts
src/service/interface.ts
src/service/types.ts
src/utils/fetch-client.ts

Closes https://github.com/AtB-AS/kundevendt/issues/8612
Nivel API documentation: https://drive.google.com/file/d/1ZkxN4s544oOmatZ1j3ADOQw-3FXfqgYE/view
This BFF implementation is basically just a pass through of the Nivel api, with the exception of their api key which is added by BFF

feat: Report mobility parking violations through Nivel API

---

src/api/mobility/index.ts

Fixes comments from merged pr: https://github.com/AtB-AS/atb-bff/pull/295#pullrequestreview-1637219146

chore: Remove whitespace

---

package-lock.json
package.json

Required to make changes in https://github.com/AtB-AS/atb-bff/pull/295 work

chore: Add dotenv as dependency

---

src/api/mobility/schema.ts
src/service/impl/mobility/index.ts
src/service/types.ts
src/utils/fetch-client.ts

Minor fixes required to make Nivel reporting work. 
The changes in `src/utils/fetch-client.ts` are not as breaking as they look, as the `post` function is not in use in any other place.
https://github.com/AtB-AS/kundevendt/issues/7908

fix: Nivel report updates

---

src/graphql/graphql-client.ts

This is TEMPORARY, I am gonna revert it afterwards.

add old logger as well

---

src/graphql/graphql-client.ts

also reverts b8fb7b84bf1fffb894026da395c5e5567a9f1491

feat: add 20 second timeout to apollo client fetch

---

src/graphql/graphql-client.ts

Rewrites fetchWithTimeout to now cancel request without using AbortSignals, which was failing before. Timeouts are now logged as:
```
{
"severity": "INFO",
"time": "2023-12-13T09:05:39.946Z",
"message": "graphql call",
"correlationId": "bbadaaf4-e347-4bb9-99c6-aa31b957c990",
"rateLimitGroup": "other",
"duration": "113ms",
"error": "[Network error]: Error: TIMEOUT"
}
{
"time": "2023-12-13T09:05:39.819Z",
"method": "GET",
"url": "http://localhost:8080/bff/v2/stop-places/mode",
"correlationId": "bbadaaf4-e347-4bb9-99c6-aa31b957c990",
"message": "handle request",
"authorities_0": "ATB:Authority:2",
"transportModes_0": "water",
"transportSubmodes_0": "highSpeedVehicleService",
"error": "TIMEOUT",
"code": "500",
"severity": "ERROR",
"duration": "132ms"
}
```
We should probably not return 500 …

fix: fix fetchWithTimeout

---

src/graphql/journey/journeyplanner-types_v3.ts
src/graphql/vehicles/vehicles-types_v1.ts
src/service/impl/departures/journey-gql/departures.graphql
src/service/impl/departures/journey-gql/departures.graphql-gen.ts

closes https://github.com/AtB-AS/kundevendt/issues/16257
App part: https://github.com/AtB-AS/mittatb-app/pull/4224

feat: add transport mode on serviceJourney in departures

---

src/api/vipps-login/index.ts

ref. https://github.com/AtB-AS/kundevendt/issues/18534

chore: mark vipps endpoints as deprecated

---

src/api/trips/index.ts
src/service/impl/mobility/index.ts
src/service/impl/trips/utils.ts

closes https://github.com/AtB-AS/kundevendt/issues/18059

chore: add logging on validation errors

---

.github/workflows/api-tests.yml
test/src/utils/headers.ts

The API-tests was missing app version.

test: add app version to API tests

---

src/service/impl/stop-places/index.ts

This reverts commit 0bc5fd48ec1d32ee27fad267eed93316270ddc18.

revert: flag to include ferry submode in stop places query

---

test/src/v2/testData/testData.ts

Add new quay Prinsen P4 to the test data that verifies a response.

test: add prinsen p4

---

.github/workflows/lint.yml

same as https://github.com/AtB-AS/mittatb-app/pull/5053

ci: use `actions/cache@v3`

---

test/src/v2/testData/testData.ts

Update line name on 82 towards `Hesttrøa`.

test: update line name

---

src/graphql/graphql-client.ts
src/service/impl/mobility/index.ts

Closes https://github.com/AtB-AS/kundevendt/issues/20230

made getvehicle query go to dev when in staging

---

src/api/trips/schema.ts
src/service/impl/trips/booking-utils.ts
src/types/trips.ts

Closes AtB-AS/kundevendt#20849

feat: Added count-check for booking endpoint

---

src/api/enrollment/index.ts
src/config/env.ts

closes https://github.com/AtB-AS/kundevendt/issues/20931
Adds checks for invites to bonus program pilot

feat: add bonus invite key checks

---

src/graphql/graphql-client.ts
src/service/impl/trips/trips.ts

Used for debugging issue that turned out to be Entur-issue :)

Revert debug logging

---

src/api/stop-places/types.ts
src/service/impl/stop-places/index.ts

fix: Fixed bug where distances were validated as object, not array

fix: Fixed bug where distances were validated as object, not array
